### ISSUE TITLE
Is the enriched slag/others on the tech tree?

### ISSUE THREAD

**Issue by dennisjosh16** [EasyPlaySu/BBM#50]
I can't find where to research the other items especially the enriched slag. Is it not in the tech tree? I'm so confused.

**Comment by MindustryRu** [comment]
@dennisjosh16 
No, everything that is in the mod is available immediately.

**Comment by dennisjosh16** [comment]
Oh, because some of them dont show up when I'm in a campaign. So i tried looking in the tech tree if i already researched the item/blocks but nothing shows up.

**Comment by MindustryRu** [comment]
In the company, this mod will not function since the game will not spawn ores. Use custom maps to play with this mod.

**Comment by dennisjosh16** [comment]
Thanks! It's a great mod tho. Unfortunately I can't play it fully on the campaign.
